function Hd = BP
%BP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 03-Dec-2020 01:23:46

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 11025;  % Sampling Frequency

Fstop1 = 500;             % First Stopband Frequency
Fpass1 = 550;             % First Passband Frequency
Fpass2 = 2000;            % Second Passband Frequency
Fstop2 = 2200;            % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
flag   = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
                             1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
