function Hd = BS
%BS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 03-Dec-2020 22:15:34

% FIR Window Bandstop filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 11025;  % Sampling Frequency

Fpass1 = 350;               % First Passband Frequency
Fstop1 = 400;               % First Stopband Frequency
Fstop2 = 525;               % Second Stopband Frequency
Fpass2 = 575;               % Second Passband Frequency
Dpass1 = 0.057501127785;    % First Passband Ripple
Dstop  = 1.5848931925e-05;  % Stopband Attenuation
Dpass2 = 0.057501127785;    % Second Passband Ripple
flag   = 'scale';           % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 ...
                             0 1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
