function Hd = LowPass
%LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 03-Dec-2020 01:04:52

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 11025;  % Sampling Frequency

Fpass = 1900;            % Passband Frequency
Fstop = 2000;            % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 1e-05;           % Stopband Attenuation
flag  = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fpass Fstop]/(Fs/2), [1 0], [Dstop Dpass]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
