function Hd = LP
%LP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 03-Dec-2020 20:44:52

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 11025;  % Sampling Frequency

Fpass = 2000;              % Passband Frequency
Fstop = 2100;              % Stopband Frequency
Dpass = 0.057501127785;    % Passband Ripple
Dstop = 1.5848931925e-05;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
